### ISSUE TITLE
Estoy perdido

### ISSUE THREAD

**Issue by casp** [yellowme/ios-course#1]
No conozco... y creo que hace falta agregar pantallas descriptivas... así como un flujo de proceso inicial. de que es lo que se utiliza y porque.

**Comment by luisburgos** [comment]
Hola!

Te entiendo totalmente, el "disclaimer" del curso por ahora es que fue un complemento del curso presencial que impartimos entonces hace mucho sentido que queden lagunas donde no se tienen la información completa 😅

¿Qué opinas de ayudarme a listar las secciones donde identificaste que necesitamos pantallas o más recursos de información? 🙌🏻
